# Generated by Django 6.0 on 2026-01-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='bmr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='carb_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='fat_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='goal_calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='ibw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='meal_plan',
            field=models.CharField(default='3', max_length=10),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='prot_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='specialist_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='tdee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
