# Generated by Django 6.0 on 2026-01-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_patientprofile_bmi_patientprofile_bmr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
