# Generated by Django 5.2.10 on 2026-01-16 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories_per_100g', models.FloatField()),
                ('carbs', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('meal_category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner')], max_length=20)),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('allergens', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='preference',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], default='Vegetarian', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientMealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=20)),
                ('calories', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.checkup')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion_g', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.fooditem')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.patientmealplan')),
            ],
        ),
    ]
