# Generated by Django 6.0.1 on 2026-01-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_fooditem_patient_preference_patientmealplan_mealfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealfood',
            name='food',
        ),
        migrations.RemoveField(
            model_name='mealfood',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='patientmealplan',
            name='checkup',
        ),
        migrations.RemoveField(
            model_name='patientmealplan',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='preference',
        ),
        migrations.AlterField(
            model_name='checkup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='MealFood',
        ),
        migrations.DeleteModel(
            name='PatientMealPlan',
        ),
    ]
