# Generated by Django 6.0.1 on 2026-01-24 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_remove_mealfood_food_remove_mealfood_meal_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkup',
            name='visit_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.AddField(
            model_name='checkup',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkup',
            name='dietary',
            field=models.CharField(default='Non-Veg', max_length=50),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='bp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
