# Generated by Django 6.0.1 on 2026-01-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_remove_checkup_visit_date_remove_patient_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='plan_type',
            field=models.CharField(default='3-Meal', max_length=20),
        ),
    ]
