# Generated by Django 6.0.1 on 2026-01-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_checkup_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20)),
                ('diet_type', models.CharField(choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non-Vegetarian'), ('Vegan', 'Vegan')], max_length=20)),
                ('calories', models.IntegerField(help_text='Calories per serving')),
                ('protein', models.FloatField(help_text='Protein (g)')),
                ('carbs', models.FloatField(help_text='Carbs (g)')),
                ('fat', models.FloatField(help_text='Fats (g)')),
                ('is_diabetes_safe', models.BooleanField(default=False, verbose_name='Diabetic Safe?')),
                ('is_high_protein', models.BooleanField(default=False, verbose_name='Renal/High Protein?')),
                ('serving_desc', models.CharField(default='1 Serving', max_length=50, verbose_name='Serving Size')),
            ],
        ),
    ]
