# Generated by Django 6.0.1 on 2026-01-31 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('meal_type', models.CharField(max_length=20)),
                ('assigned_calories', models.IntegerField()),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.checkup')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.fooditem')),
            ],
        ),
    ]
