# Generated by Django 6.0.1 on 2026-01-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_assignedmeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='is_high_protein',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_cardiac_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_hypertension_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_renal_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sodium',
            field=models.FloatField(default=0, help_text='mg'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sugar',
            field=models.FloatField(default=0, help_text='g'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.CharField(default='None', help_text='e.g., Diabetes, Hypertension, Renal', max_length=200),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='diet_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Vegan', 'Vegan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='is_diabetes_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='serving_desc',
            field=models.CharField(default='1 Serving', max_length=50),
        ),
    ]
