# Generated by Django 6.0.1 on 2026-01-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_remove_fooditem_is_high_protein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
    ]
