# Generated by Django 6.0.1 on 2026-01-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_alter_patient_medical_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedmeal',
            old_name='assigned_calories',
            new_name='total_calories',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='serving_desc',
        ),
        migrations.AddField(
            model_name='assignedmeal',
            name='quantity_text',
            field=models.CharField(default='1 Serving', max_length=50),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fiber',
            field=models.FloatField(default=0, help_text='g'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.TextField(default='', help_text='Comma separated for allergy checking'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='phosphorus',
            field=models.FloatField(default=0, help_text='mg (Critical for Renal)'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='potassium',
            field=models.FloatField(default=0, help_text='mg (Critical for Renal)'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='unit_name',
            field=models.CharField(default='Serving', help_text='e.g. Cup, Pcs, Bowl', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.CharField(default='None', help_text='Comma separated ingredients to avoid', max_length=200),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.IntegerField(help_text='Calories per unit/serving'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.CharField(default='None', help_text='diabetes, renal, hypertension, cardiac', max_length=200),
        ),
    ]
