# Generated by Django 6.0.1 on 2026-01-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_rename_assigned_calories_assignedmeal_total_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='fiber',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='ingredients',
            field=models.TextField(default='', help_text='For allergy check'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='phosphorus',
            field=models.FloatField(default=0, help_text='mg (Renal)'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='potassium',
            field=models.FloatField(default=0, help_text='mg (Renal)'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='unit_name',
            field=models.CharField(default='Serving', help_text='e.g. Idli, Cup', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(default='None', help_text='Comma separated ingredients', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.CharField(default='None', help_text='diabetes, renal, cardiac', max_length=200),
        ),
    ]
