# Generated by Django 6.0.1 on 2026-01-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_remove_fooditem_fiber_alter_fooditem_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='serving_desc',
            field=models.CharField(default='1 Serving', max_length=50),
        ),
    ]
