# Generated by Django 6.0.1 on 2026-02-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_fooditem_serving_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkup',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='is_cardiac_safe',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='is_diabetes_safe',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='is_hypertension_safe',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='is_renal_safe',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='phosphorus',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='checkup',
            name='carbs_target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='checkup',
            name='fat_target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='checkup',
            name='protein_target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fiber',
            field=models.FloatField(default=0, help_text='Important for Obese/Weight Loss'),
        ),
        migrations.AlterField(
            model_name='assignedmeal',
            name='quantity_text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='activity',
            field=models.FloatField(help_text='Multiplier (1.2 - 1.9)'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='height',
            field=models.FloatField(help_text='cm'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='weight',
            field=models.FloatField(help_text='kg'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='sugar',
            field=models.FloatField(default=0, help_text='Filter for unhealthy items'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='unit_name',
            field=models.CharField(default='Serving', help_text='e.g. Cup, Nos', max_length=20),
        ),
    ]
