# Generated by Django 6.0.1 on 2026-02-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_remove_checkup_bp_remove_checkup_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='blood_pressure',
            field=models.CharField(default='120/80', max_length=20),
        ),
    ]
