# Generated by Django 6.0.1 on 2026-03-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_checkup_blood_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='diseases',
            field=models.CharField(blank=True, help_text='Comma-separated diseases', max_length=200),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sodium',
            field=models.FloatField(default=0, help_text='mg per 100g'),
        ),
    ]
