# Generated by Django 6.0.1 on 2026-03-06 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0018_checkup_diseases_fooditem_sodium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('priority', models.IntegerField(default=5, help_text='1 = low priority, 10 = highest (overrides conflicts)')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='calcium',
            field=models.FloatField(default=0, help_text='mg per 100 g'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='phosphorus',
            field=models.FloatField(default=0, help_text='mg per 100 g'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='potassium',
            field=models.FloatField(default=0, help_text='mg per 100 g'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='activity',
            field=models.FloatField(help_text='Multiplier (1.2 – 1.9)'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='diseases',
            field=models.CharField(blank=True, help_text='Auto-synced comma-separated names from disease_links.', max_length=500),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='sodium',
            field=models.FloatField(default=0, help_text='mg per 100 g'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='unit_name',
            field=models.CharField(default='Serving', max_length=20),
        ),
        migrations.AddField(
            model_name='checkup',
            name='disease_links',
            field=models.ManyToManyField(blank=True, help_text='Select all applicable diseases for this checkup.', to='health.disease', verbose_name='Medical Conditions'),
        ),
        migrations.CreateModel(
            name='NutrientLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient', models.CharField(choices=[('sodium', 'Sodium (mg)'), ('sugar', 'Sugar (g)'), ('fat', 'Fat (g)'), ('carbs', 'Carbs (g)'), ('protein', 'Protein (g)'), ('fiber', 'Fiber (g)'), ('calcium', 'Calcium (mg)'), ('potassium', 'Potassium (mg)'), ('phosphorus', 'Phosphorus (mg)')], max_length=30)),
                ('max_daily_g', models.FloatField(blank=True, help_text='Daily upper limit (g or mg). NULL = use smart default.', null=True)),
                ('is_banned', models.BooleanField(default=False, help_text='If True: any food containing this nutrient is excluded.')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_limits', to='health.disease')),
            ],
            options={
                'unique_together': {('disease', 'nutrient')},
            },
        ),
    ]
