# Generated by Django 6.0.3 on 2026-03-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0019_disease_fooditem_calcium_fooditem_phosphorus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='restricted_nutrients',
            field=models.JSONField(default=dict, help_text='Format: {"sodium": {"banned": false, "max": 1500}, "sugar": {"banned": true}}'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='NutrientLimit',
        ),
    ]
